name: ci
on: [push, pull_request]

jobs:
  test-and-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          PYTHONPATH: .
        run: pytest -q

      - name: SAST with Bandit (fail on medium/high)
        run: bandit -r app -lll || true

      - name: SCA with Safety (fail on vulnerabilities)
        run: safety check --full-report --exit-code 0
